.\" Manpage for ochtendzon
.TH TAU 1 "18 Nov 2025" "0.1.0"

.SH NAME
tau \- Compiler for the Tau language.

.SH SYNOPSIS
.B tau
[\fIFILE\fR]...

.SH DESCRIPTION
The \fBtau\fR command takes a single Tau files and compiles it to the default target (e.g. C++). If no file was passed, it will instead start in REPL mode.

.SH EXAMPLES
tau example/main.tau

.SH REPORTING BUGS
You can report a bugs on GitHub <https://github.com/tau-lang/tau/issues>

.SH SEE ALSO
ochtendzon(1)

.SH COPYRIGHT
Licensed under the EUPL