[package]
name = "tau-lang"
version = "0.1.0"
edition = "2024"
authors = ["Lovis Rentsch", "Karl Zschiebsch"]
description = "compiler"
license-file = "./LICENSE"
rust-version = "1.85"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = { version = "7.6.0", features = ["fancy"] }
pest = "2.8.0"
pest_derive = "2.8.0"
thiserror = "2.0.12"
