[package]
name = "tau-lang"
version = "0.1.0"
edition = "2024"
authors = ["Lovis Rentsch", "Karl Zschiebsch"]
description = "compiler"
license-file = "./LICENSE"
rust-version = "1.85"

[features]
cranelift = ["dep:cranelift", "dep:cranelift-module", "dep:cranelift-object"]
ctranspiler = []
default = ["cranelift"]

[dependencies]
cranelift = { version = "0.121.2", optional = true }
cranelift-module = { version = "0.121.2", optional = true }
cranelift-object = {version = "0.121.2", optional = true}
