root    = { SOI ~ imports ~ declarations ~ EOI }
typeDef = { name ~ ":" ~ typeName }
body    = { "{" ~ statement* ~ "}" }

imports = { import* }
import  = { "import" ~ variable }

declarations = { declaration* }
declaration  = { functionDecl | structDecl | variableDecl }
functionDecl = { "fn" ~ name ~ "(" ~ (typeDef ~ ("," ~ typeDef)*)? ~ ")" ~ (":" ~ typeName) ~ body }
structDecl   = { "struct" ~ name ~ "{" ~ (typeDef ~ ("," ~ typeDef)*)? ~ "}" }
variableDecl = { variableStatement | constantStatement }

controlFlow = { ifFlow | whileFlow | forFlow }
ifFlow      = { "if" ~ boolExpr ~ body ~ (elseIfFlow)* ~ (elseFlow)? }
elseFlow    = { "else" ~ body }
elseIfFlow  = { "else" ~ "if" ~ boolExpr ~ body }
whileFlow   = { "while" ~ boolExpr ~ body }
forFlow     = { "for" ~ name ~ "in" ~ iterExpr ~ body }

statement             = {
    variableStatement
  | constantStatement
  | modificationStatement
  | callStatement
  | returnStatement
  | breakStatement
  | controlFlow
}
variableStatement     = { "let" ~ typeDef ~ "=" ~ valueExpr }
constantStatement     = { "const" ~ typeDef ~ "=" ~ valueExpr }
modificationStatement = { variable ~ ((assignOp ~ valueExpr) | unaryInc | unaryDec) }
callStatement         = { variable ~ "(" ~ (valueExpr ~ (", " ~ valueExpr)*)? ~ ")" }
returnStatement       = { "return" ~ valueExpr }
breakStatement        = { "break" }

valueExpr  = { variable | arrayExpr | tableExpr | numberExpr | boolExpr | char | string }
arrayExpr  = { "[" ~ (valueExpr ~ ("," ~ valueExpr)*)? ~ "]" }
tableExpr  = { "{" ~ (tablePair ~ ("," ~ tablePair)*)? ~ "}" }
tablePair  = { name ~ "=" ~ valueExpr }
numberExpr = {
    "(" ~ numberExpr ~ ")"
  | number ~ (mul | div) ~ number
  | number ~ (add | sub) ~ number
  | number
  | variable
}
boolExpr   = {
    "(" ~ boolExpr ~ ")"
  | numberExpr ~ (gre | low | geq | leq | eq | neq) ~ numberExpr
  | "!" ~ bool
  | bool
  | variable
}
iterExpr   = { name | callStatement }

variable = @{ name ~ ("." ~ name)* }
name     = @{ (ASCII_ALPHA) ~ (ASCII_ALPHA | ASCII_DIGIT)* }
number   =  { float | integer }
float    = @{ ("+" | "-")? ~ (ASCII_NONZERO_DIGIT ~ ASCII_DIGIT* | "0") ~ "." ~ ASCII_DIGIT+ }
integer  = @{ ("+" | "-")? ~ (ASCII_NONZERO_DIGIT ~ ASCII_DIGIT* | "0") }
bool     = @{ "true" | "false" }
char     = @{ "'" ~ ANY ~ "'" }
string   = @{ "\"" ~ (ASCII)* ~ "\"" }

typeName = @{
    native
  | name
}
native   = @{
    "bool"
  | "char"
  | "string"
  | "i8"
  | "i16"
  | "i32"
  | "i64"
  | "u8"
  | "u16"
  | "u32"
  | "u64"
  | "f32"
  | "f64"
}

assignOp  =  {
    assign
  | addAssign
  | subAssign
  | mulAssign
  | divAssign
}
assign    = @{ "=" }
addAssign = @{ "+=" }
subAssign = @{ "-=" }
mulAssign = @{ "*=" }
divAssign = @{ "/=" }
unaryInc  = @{ "++" }
unaryDec  = @{ "--" }

add = @{ "+" }
sub = @{ "-" }
mul = @{ "*" }
div = @{ "/" }
gre = @{ ">" }
low = @{ "<" }
geq = @{ ">=" }
leq = @{ "<=" }
eq  = @{ "==" }
neq = @{ "!=" }

WHITESPACE = _{ " " | "\t" | NEWLINE }
COMMENT    = _{ "//" ~ (!NEWLINE ~ ANY)* }
